#█__█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗ █
#█  ╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝ █
#█  ██████╗░░█████╗░██████╗░████████╗██╗░█████╗░██╗░░░░░███████╗  ░██████╗░██╗░░░██╗███╗░░██╗  █
#█  ██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██║██╔══██╗██║░░░░░██╔════╝  ██╔════╝░██║░░░██║████╗░██║  █
#█  ██████╔╝███████║██████╔╝░░░██║░░░██║██║░░╚═╝██║░░░░░█████╗░░  ██║░░██╗░██║░░░██║██╔██╗██║  █
#█  ██╔═══╝░██╔══██║██╔══██╗░░░██║░░░██║██║░░██╗██║░░░░░██╔══╝░░  ██║░░╚██╗██║░░░██║██║╚████║  █
#█  ██║░░░░░██║░░██║██║░░██║░░░██║░░░██║╚█████╔╝███████╗███████╗  ╚██████╔╝╚██████╔╝██║░╚███║  █
#█  ╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░╚════╝░╚══════╝╚══════╝  ░╚═════╝░░╚═════╝░╚═╝░░╚══╝  █
#█  █████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗ █
#█__╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝ █
#%player% to show all players on the server